### ISSUE TITLE
Bad link to Downloads page

### ISSUE THREAD

**Issue by jeffbarr** [penn-nlp/mmid#1]
The Downloads link on your main page (https://github.com/penn-nlp/mmid) links to https://github.com/penn-nlp/mmid/blob/master/downloads.html, which is not present, and returns a 404.

**Comment by john-hewitt** [comment]
Good catch; thanks. The link works on our site https://multilingual-images.org, but not on the readme. Will fix soon.

**Comment by john-hewitt** [comment]
I replaced the relative links with absolute links rooted at https://multilingual-images.org. This means navigating via links in github won't be possible, but I think I like that behavior because the hosted pages are the intended interface anyway. Feel free to reopen if you have other concerns.
